### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by christophberger** [polarsource/polar-go#4]
Awesome to see a Polar Go SDK!

Please add a license file so that pkg.go.dev will [display the documentation](https://pkg.go.dev/github.com/polarsource/polar-go@v0.0.4#section-documentation).

Thank you!

![Screenshot 2024-12-20 at 16 45 44](https://github.com/user-attachments/assets/a83a9096-6a65-45cc-81b8-6119ebf2e284)

**Comment by emilwidlund** [comment]
Great idea! MIT License added :)

**Comment by christophberger** [comment]
Now. That. Was. Fast. 🤯

**Comment by christophberger** [comment]
@emilwidlund  BTW, it [seems](https://github.com/golang/go/issues/48919#issuecomment-940989842) that pkg.go.dev needs to see a version update to re-scan the repo for a license.
